require("indent_blankline").setup {
    indent_blankline_filetype_exclude = {
        "help",
        "Trouble",
        "text",
        "alpha",
    },
    indent_blankline_context_patterns = {
        "class",
        "return",
        "function",
        "method",
        "^if",
        "^while",
        "^for",
        "^object",
        "^table",
        "block",
        "arguments",
        "if_statement",
        "else_clause",
        "try_statement",
        "catch_clause",
        "import_statement",
        "operation_type",
    },
}
