require "u.pluginsettings.cmp"
require "u.pluginsettings.colourscheme"
require "u.pluginsettings.comment"
require "u.pluginsettings.lsp"
require "u.pluginsettings.nvimtree"
require "u.pluginsettings.telescope"
require "u.pluginsettings.treesitter"
require "u.pluginsettings.whichkey"
