require("nvim-navbuddy").setup {
   icons = {
      -- from ? (possibly neovim from scratch)
      Array = " ",
      Boolean = "蘒",
      Key = " ",
      Namespace = " ",
      Null = "ﳠ ",
      Number = " ",
      Object = " ",
      Package = " ",
      String = " ",
      -- from lspkind
      Method = " ",
      Function = " ",
      Constructor = " ",
      Field = "ﰠ ",
      Variable = " ",
      Class = "ﴯ ",
      Interface = " ",
      Module = " ",
      Property = "ﰠ ",
      Enum = " ",
      File = " ",
      EnumMember = " ",
      Constant = " ",
      Struct = "פּ ",
      Event = " ",
      Operator = " ",
      TypeParameter = "",
   },
}
