-- ██████╗░██╗░░░░░██╗░░░██╗░██████╗░░░░░░░░█████╗░██████╗░████████╗░░░██╗░░░░░██╗░░░██╗░█████╗░
-- ██╔══██╗██║░░░░░██║░░░██║██╔════╝░░░░░░░██╔══██╗██╔══██╗╚══██╔══╝░░░██║░░░░░██║░░░██║██╔══██╗
-- ██████╔╝██║░░░░░██║░░░██║██║░░██╗░█████╗██║░░██║██████╔╝░░░██║░░░░░░██║░░░░░██║░░░██║███████║
-- ██╔═══╝░██║░░░░░██║░░░██║██║░░╚██╗╚════╝██║░░██║██╔═══╝░░░░██║░░░░░░██║░░░░░██║░░░██║██╔══██║
-- ██║░░░░░███████╗╚██████╔╝╚██████╔╝░░░░░░╚█████╔╝██║░░░░░░░░██║░░░██╗███████╗╚██████╔╝██║░░██║
-- ╚═╝░░░░░╚══════╝░╚═════╝░░╚═════╝░░░░░░░░╚════╝░╚═╝░░░░░░░░╚═╝░░░╚═╝╚══════╝░╚═════╝░╚═╝░░╚═╝
-- a b c d e f g h i j k l m n o p q r s t u v w x y z
-- folders:
require "plugin-settings.lsp"
require "plugin-settings.completion"

-- files:
require "plugin-settings.alpha"
require "plugin-settings.autopairs"
require "plugin-settings.colorizer"
require "plugin-settings.colourscheme"
require "plugin-settings.comment"
-- require "plugin-settings.dap"
require "plugin-settings.dial"
require "plugin-settings.drop"
require "plugin-settings.duck"
require "plugin-settings.gitsigns"
require "plugin-settings.gitconflict"
require "plugin-settings.hlargs"
require "plugin-settings.illuminate"
require "plugin-settings.impatient"
require "plugin-settings.indentline"
require "plugin-settings.lualine"
require "plugin-settings.luasnip"
require "plugin-settings.navic"
require "plugin-settings.neoscroll"
require "plugin-settings.noice"
require "plugin-settings.notify"
require "plugin-settings.numb"
require "plugin-settings.nvim-tree"
-- require "plugin-settings.project"
require "plugin-settings.renamer"
require "plugin-settings.scrollbar"
require "plugin-settings.surround"
require "plugin-settings.tablineopt"
require "plugin-settings.tabout"
require "plugin-settings.telescope"
require "plugin-settings.temp-string"
require "plugin-settings.tint"
require "plugin-settings.toggleterm"
require "plugin-settings.treesitter"
require "plugin-settings.ts-context"
require "plugin-settings.ufo"
require "plugin-settings.webdev-icons"
require "plugin-settings.which-key"
require "plugin-settings.winsep"
