return {
	{
		"catppuccin/nvim",
		opts = {
			transparent_background = true,
			show_end_of_buffer = true,
			styles = {
				loops = { "italic" },
				functions = { "bold" },
				keywords = { "italic" },
			},
			custom_highlights = function(c)
				return {
					TreesitterContextBottom = { bold = true, underline = true },
					LineNrAbove = { fg = c.overlay0 },
					LineNrBelow = { fg = c.overlay0 },
					Pmenu = { fg = c.pink },
					CmpItemAbbrMatch = { fg = c.maroon, bold = true },
					CmpItemMenu = { italic = true },
					Visual = { bold = true, reverse = true },
					TelescopeSelection = { bg = c.surface1, style = { "bold" } },
					TelescopeSelectionCaret = { bg = c.surface1, style = { "bold" } },
					TelescopeBorder = { fg = c.pink },
					GitSignsChangedelete = { fg = c.blue },
					EndOfBuffer = { fg = c.overlay0 },
					Whitespace = { fg = c.overlay0 },
					VertSplit = { fg = c.overlay0 },
					TabLine = { fg = c.text, bg = "None" },
					TabLineSel = { fg = c.text, bg = "None", reverse = true },
				}
			end,
			integrations = {
				alpha = true,
				aerial = false,
				barbar = false,
				beacon = false,
				cmp = true,
				coc_nvim = false,
				dashboard = false,
				fern = false,
				fidget = true,
				gitgutter = false,
				gitsigns = true,
				harpoon = true,
				headlines = false,
				hop = false,
				illuminate = false,
				leap = false,
				lightspeed = false,
				lsp_saga = false,
				lsp_trouble = true,
				markdown = true,
				mason = true,
				mini = true,
				neogit = false,
				neotest = false,
				neotree = false,
				noice = false,
				notify = false,
				nvimtree = false,
				octo = false,
				overseer = false,
				pounce = false,
				sandwich = false,
				semantic_tokens = true,
				symbols_outline = false,
				telekasten = false,
				telescope = true,
				treesitter = true,
				treesitter_context = true,
				ts_rainbow = false,
				ts_rainbow2 = false,
				vim_sneak = false,
				vimwiki = false,
				which_key = false,
				dap = { enabled = true, enable_ui = true },
				indent_blankline = { enabled = false, colored_indent_levels = false },
				native_lsp = { enabled = true },
				navic = { enabled = false },
			},
		},
		config = function(_, opts)
			require("catppuccin").setup(opts)
			vim.cmd.colorscheme "catppuccin"

			-- print palette
			vim.keymap.set(
				"n",
				"<leader><leader>h",
				"<cmd>lua pp(require('catppuccin.palettes').get_palette 'mocha')<cr>",
				{ desc = "Get Palette" }
			)
		end,
		lazy = false,
		priority = 1000,
	},
}
